### ISSUE TITLE
lassosum tutorial

### ISSUE THREAD

**Issue by tshmak** [choishingwan/choishingwan.github.io#1]
Hi Sam, 

Thanks for doing a tutorial for lassosum on your site! Just a few suggestions on the instructions: 

1. With the newest version of lassosum, you can actually just specify LDscores = "EUR.hg19" to use the "Berisa.EUR.hg19.bed" LD regeions. 
2. You may also consider mentioning the parallel processing capabilities in the tutorial. Perhaps just refer the reader to my tutorial. 

Thanks a lot!

**Comment by choishingwan** [comment]
Hi Tim,

Which part of the pipeline should we specify the LDscores = "EUR.hg19"?
Didn't see that option in the lassosum.pipeline function.

**Comment by choishingwan** [comment]
Also, double check with you:

cl <- makeCluster(2, type="FORK")

uses 2 threads, right? Based on the documentation, the 2 is specific, not
nnode, which is kinda confusing. Side note: USing type="FORK" means that
the multithreading won't work on windows.

**Comment by tshmak** [comment]
As in instead of 
```
ld.file <- system.file("data", "Berisa.EUR.hg19.bed",package="lassosum")
ld <- fread(ld.file)
out <- lassosum.pipeline(..., LDblocks = ld)
```
one can simply specify, 
```
out <- lassosum.pipeline(..., LDblocks = "EUR.hg19")
```

**Comment by tshmak** [comment]
No, 2 is the number of nodes in `makeCluster`. I suppose other types than `FORK` may also work, but I haven't really tried.

**Comment by choishingwan** [comment]
Got it updated. Was wondering where this issue was located. End up finding it in my personal website, haha
